name: 'Python Setup Rye'
description: 'Set up and cache rye and add it to the PATH'
author: 'eifinger'
inputs:
  version: 
    description: 'The version of rye to install'
    default: 'latest'
  checksum:
    description: 'The checksum of the rye version to install'
    required: false
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
branding:
  icon: 'package'
  color: 'blue'
