name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Should not be on path
        run: |
          which rye
        continue-on-error: true
      - name: Install latest
        uses: ./
      - run: |
          which rye
  test-specific-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install specific version
        uses: ./
        with:
          version: '0.11.0'
      - run: |
          which rye
  test-checksum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checksum matches expected
        uses: ./
        with:
          version: '0.11.0'
          checksum: '00e795573477a2fe2b3c0ac748240364c3369218d314d1df47d2653764e9bfb1'
