name: 'test-cache'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-setup-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup with cache
        uses: ./
        with:
          version: '0.11.0'
          enable-cache: true
      - run: |
          which rye
  test-restore-cache:
    runs-on: ubuntu-latest
    needs: test-setup-cache
    steps:
      - uses: actions/checkout@v3
      - name: Restore with cache
        uses: ./
        with:
            version: '0.11.0'
            enable-cache: true
      - run: which rye
      - name: Cache was hit
        run: |
          if [ "$CACHE_HIT" != "true" ]; then
            exit 1
          fi
        env:
          CACHE_HIT: ${{ needs.test-setup-cache.outputs.cache-hit }}
