name: 'test-latest'
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, oracle-aarch64]
        enable-cache: [true, false]
    steps:
      - uses: actions/checkout@v4
      - name: Should not be on path
        run: |
          if ! which rye;
          then
            exit 0
          else
           exit 1
          fi
      - name: Setup rye
        uses: ./
        with:
          version: latest
          working-directory: __tests__/fixtures/rye-project
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-cache: ${{ matrix.enable-cache }}
      - run: rye sync
        working-directory: __tests__/fixtures/rye-project
      - name: Rye path is not added to .profile
        run: |
          if ! grep -q "rye" ~/.profile;
          then
            exit 0
          else
            exit 1
          fi
  test-latest-without-github-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rye
        uses: ./
        with:
          version: latest
      - run: rye sync
        working-directory: __tests__/fixtures/rye-project

  test-latest-automatic-toolchain:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, oracle-aarch64]
    steps:
      - uses: actions/checkout@v4
      - name: Determine expected python version
        id: determine-expected-python-version
        run: |
          EXPECTED_PYTHON_VERSION=$(cat .python-version)
          echo "EXPECTED_PYTHON_VERSION=$EXPECTED_PYTHON_VERSION" >> "$GITHUB_OUTPUT"
        working-directory: __tests__/fixtures/rye-project
      - name: Setup rye
        uses: ./
        with:
          version: latest
          working-directory: __tests__/fixtures/rye-project
      - run: rye sync
        working-directory: __tests__/fixtures/rye-project
      - name: Check python version
        run: |
          ACTUAL_PYTHON_VERSION=$(ls $RYE_HOME/py)
          if [ "$ACTUAL_PYTHON_VERSION" != "$EXPECTED_PYTHON_VERSION" ];
          then
            echo "$ACTUAL_PYTHON_VERSION is not the same as $EXPECTED_PYTHON_VERSION"
            exit 1
          fi
        env:
          EXPECTED_PYTHON_VERSION: ${{ steps.determine-expected-python-version.outputs.EXPECTED_PYTHON_VERSION }}
