name: 'test-latest'
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, oracle-aarch64]
        enable-cache: [true, false]
    steps:
      - uses: actions/checkout@v4
      - name: Should not be on path
        run: |
          if ! which rye;
          then
            exit 0
          else
           exit 1
          fi
      - name: Setup rye
        uses: ./
        with:
          version: latest
          working-directory: __tests__/fixtures/rye-project
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-cache: ${{ matrix.enable-cache }}
      - run: rye sync
        working-directory: __tests__/fixtures/rye-project
      - name: Rye path is not added to .profile
        run: |
          if ! grep -q "rye" ~/.profile;
          then
            exit 0
          else
            exit 1
          fi
  test-latest-without-github-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rye
        uses: ./
        with:
          version: latest
      - run: rye sync
        working-directory: __tests__/fixtures/rye-project
  test-latest-with-uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rye
        uses: ./
        with:
          version: latest
      - run: |
          rye config --set-bool behavior.use-uv=true
          rye sync
        working-directory: __tests__/fixtures/rye-project