name: 'test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, oracle-aarch64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm install
      - run: |
          npm run all
  test-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, oracle-aarch64]
    steps:
      - uses: actions/checkout@v4
      - name: Should not be on path
        run: |
          if ! which rye;
          then
            exit 0
          else
           exit 1
          fi
      - name: Install latest
        uses: ./
      - run: |
          which rye
  test-specific-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, oracle-aarch64]
        rye-version: ['0.11.0', '0.12.0', '0.13.0', '0.14.0']
    steps:
      - uses: actions/checkout@v4
      - name: Install specific version
        uses: ./
        with:
          version: ${{ matrix.rye-version }}
      - run: |
          which rye
  test-checksum:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, oracle-aarch64]
        checksum: ['00e795573477a2fe2b3c0ac748240364c3369218d314d1df47d2653764e9bfb1']
        exclude:
          - os: oracle-aarch64
            checksum: '00e795573477a2fe2b3c0ac748240364c3369218d314d1df47d2653764e9bfb1'
        include:
          - os: oracle-aarch64
            checksum: '7e0b1f6e3490a79c1d2600e8c04dd9ed4ea04d29d6c80f1f5a84a79736e9a21d'
    steps:
      - uses: actions/checkout@v4
      - name: Checksum matches expected
        uses: ./
        with:
          version: '0.11.0'
          checksum: ${{ matrix.checksum }}
